name: RAR Source

on:
  workflow_run:
    workflows: ["Auto Update Working Progress"]
    types: [completed]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: write-all

env:
  RAR_SOURCE_NAME: ${{ vars.RAR_SOURCE_NAME }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rar-source:
    name: RAR Source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install rar
        run: sudo apt-get install rar

      - name: RAR source
        run: |
          touch ${{ env.RAR_SOURCE_NAME }}.txt
          echo "https://github.com/${{ github.repository }}/" > ${{ env.RAR_SOURCE_NAME }}.txt
          mkdir ${{ env.RAR_SOURCE_NAME }}
          cp -r *Bai* *.sln ${{ env.RAR_SOURCE_NAME }}.txt ${{ env.RAR_SOURCE_NAME }} 
          rar a -r ${{ env.RAR_SOURCE_NAME }}.rar ${{ env.RAR_SOURCE_NAME }}

      - name: Release RAR source code
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ env.GITHUB_TOKEN }}
          file: ${{ env.RAR_SOURCE_NAME }}.rar
          tag: RAR
          release_name: RAR Source Code
          overwrite: true
          promote: true
          body: "Rar source code để nộp bài, không bao gồm các file ngoài Visual Studio"

      - name: Release .txt
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ env.GITHUB_TOKEN }}
          file: ${{ env.RAR_SOURCE_NAME }}.txt
          tag: RAR
          release_name: RAR Source Code
          overwrite: true
          promote: true
          body: "Rar source code để nộp bài, không bao gồm các file ngoài Visual Studio"
